[project]
name = "17-deploying-open-source-endpoints"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "chromadb>=1.0.20",
    "jupyter>=1.1.1",
    "langchain>=0.3.27",
    "langchain-community>=0.3.27",
    "langgraph>=0.6.6",
    "openai>=1.100.2",
    "sentence-transformers>=5.1.0",
    "together>=1.5.25",
]
